### ISSUE TITLE
用語集ページが欲しい

### ISSUE THREAD

**Issue by b-wind** [openCACAO/cocoa-documentation#14]
Exposure Notification System 全体に言えることですが、比較的なじみの無い単語が多く正確な単語を利用しようとするほど一般の人には分からない言葉になっているように思います。

用語集としましたが、よくあるWikiシステムのように一単語一ページでも良いです。
作るのは少し面倒ですが、Wiki内でのリンクは貼りやすいと思われます。

**Comment by ghost** [comment]
@Elya-phys さんが用語集を作成してくれました。ありがとう。

少し用語を追加しました。

**Comment by b-wind** [comment]
ずいぶん前に作って貰っていたようなのでこのIssueは閉じます。
