### ISSUE TITLE
(iOS)接触日をHash値より検索するサイト(非公式) の文字化け

### ISSUE THREAD

**Issue by lucky5sugar** [openCACAO/cocoa-documentation#15]
(iOS)接触日をHash値より検索するサイト(非公式) にお世話になったものです．
有志での作成，誠にありがとうございます．

こちらのサイトですが，iPhone (iOS 13.6)とSafari (Mac OS 10.13 High Sierra)では文字化けしてしまいました．
Google chromeでは文字化けせずに開くことができました．

**Comment by Elya-phys** [comment]
lucky5sugarさん
ご報告ありがとうございます。調査したところ、文字コードの設定がShift-JISになっていたことが原因でした。対応として文字コードをUnicode(utf-8)に変更し、言語設定を日本語としました。
ご確認よろしくお願いします。

**Comment by lucky5sugar** [comment]
Elya-physさん

ご対応を誠にありがとうございます．
iPhone (iOS 13.6)とSafari (Mac OS 10.13 High Sierra)にて問題の解決を確認しました．
これからも宜しくお願い致します．
