### ISSUE TITLE
通知が表示されたが接触確認アプリを開いても「接触なし」と表示される件

### ISSUE THREAD

**Issue by teriha8t8** [openCACAO/cocoa-documentation#5]
iOS版の不具合。
8月2日深夜から出現。(蛇足:8月2日のZIPは異様だった)
8月にもなると結果ファイル詳細を見る人が増えたので容易に発覚。

7月段階では、厚労省が「通知があってもアプリに表示がなければアプリが正しい」という見解だったのでファイル詳細まで見ない人が多く、実際のところ障害の有無は不明。

8月3日〜5日は通知があってもキーの一致がない人(単なる誤通知の事例)が数名あったが、それ以降はアプリに接触情報が表示されない人ばかりか。

8月2日以前は、iPhoneでもアプリに接触情報が表示されていたのに、障害が一向に回復しない理由が不明。

**Comment by moonmile** [comment]
https://github.com/openCACAO/cocoa-issues/issues/1 へ移動しておきます。
