### ISSUE TITLE
利用開始後しばらく経ったが、利用開始画面が再度表示される件

### ISSUE THREAD

**Issue by teriha8t8** [openCACAO/cocoa-documentation#6]
iOS版の不具合。
ver1.1.2リリース直後から発生。
ホーム画面の年月日使用日数がリセットされる件も含む。

ver1.1.2リリース直後から数日おきにチュートリアルのやり直しが起きる。
久し振りにアプリを立ち上げたらチュートリアルのやり直しになった。
これらは多くないがiOS13.5から発現していた不具合。

13.5から発現していた人は13.6になって落ち着いた報告があるが、iOS13.6.1がリリースされてからは、年月日使用日数がリセットされる不具合報告がTwitter上で目立つ。

接触確認アプリCOCOAは「使用中止」を実行してもExposure Notification機能をオフにしない。
ユーザーがExposure Notification機能(「COVID-19接触通知」または「接触のログ記録」)をオフにしない限り有効のままなので、実質的に実害はない障害とみる。
(チュートリアルのやり直しになっている間だけExposure Notification機能は無効になっているだけのはず)

**Comment by moonmile** [comment]
https://github.com/openCACAO/cocoa-issues/issues/2 へ移動しておきます。
