### ISSUE TITLE
接触ありと通知されたが、陽性者と接触の心当たりがない件

### ISSUE THREAD

**Issue by teriha8t8** [openCACAO/cocoa-documentation#7]
Android版に見られる現象。

掲示板、Twitterで「アプリに表示された日は在宅しており誰とも接触していない」という書き込みが散見される。
夏休み(お盆休み)中に頻出。
接触日に1メートル以内15分以上の接触はまったく思い当たらない、という旨も多数。

Bluetooth機能(精度)の問題か？

**Comment by moonmile** [comment]
https://github.com/openCACAO/cocoa-issues/issues/3 へ移動しておきます。
