### ISSUE TITLE
機能無効、地域非対応等の表示によりインストール・利用開始できない件

### ISSUE THREAD

**Issue by teriha8t8** [openCACAO/cocoa-documentation#8]
iOS版の不具合。
7月11日から発生。

ver1.0.0 ユーザーが権限拒否をやるとアプリが実装されない致命的な不具合があった。
これを修正したとされるのがver1.1.1だが実際は修正されきっていない。

ver1.1.1
ユーザーが権限拒否(COVID-19接触のログ記録を有効にしないを選択)したとき、アプリのローカル通知(プッシュ通知)が実装されない不具合がある。
また設定でモバイル通信がオフになっていれば、モバイル通信トグルスイッチも実装されない。
ver1.1.2も同様。

7月10日まではユーザーが権限拒否をやった場合のみ実装に問題をだしていたが、7月11日以降はサーバー側が権限許諾を聞かず(COVID-19接触のログ記録を有効にするしないがでない)、最後に権限拒否(Exposure Notification機能は無効の状態です…)を返してくるようになったため、新規登録(インストール)できない障害をだしている。

過去に1度Exposure Notification機能を有効にしていれば端末に「(COVID-19)接触のログ記録」トグルスイッチが実装されているため、「COVID-19接触通知」は実装され「プッシュ通知」が実装されないだけですむが、新規登録は「COVID-19接触通知」「接触のログ記録」トグルスイッチが実装されないためExposure Notification機能を有効にすることはできない。
新規登録は、接触確認アプリが正常にインストールできていない状態で完了する。

接触確認アプリ、Exposure Notification APIの仕様を理解していなければ、インストールできていない状態に気づかないと思われる。

開発側がこの障害に気づいたのは7月末頃と推察。
7月末頃からサーバをいじりはじめたようで、サーバーから返ってくるエラーメッセージにいくつかのパターンがあるが、正常にインストールできない障害は8月26日現在も続いている。

モバイル通信でインストールすれば「COVID-19接触通知」は実装され、「プッシュ通知」が実装されないだけなので、接触確認アプリの運用は可能。
(但し、サーバーのコンディションによって「COVID-19接触通知」が実装されないときもある。)

プッシュ通知が実装されていなければアプリから接触通知を受け取れないため、ユーザーが意識して結果ファイル(接触チェックファイル)の詳細を確認する必要がある。

Wi-Fi接続では「COVID-19接触通知」が実装されないためインストール完全不可。

**Comment by moonmile** [comment]
https://github.com/openCACAO/cocoa-issues/issues/4 へ移動しておきます。
